#!/usr/bin/env python3
"""
Initialize Graphify for Autognosia.

Run this once after wiki has content:
  python3 scripts/init_graphify.py

Prerequisites:
  uv tool install graphifyy
  graphify install
"""

import os
import subprocess
import sys
from pathlib import Path

AUTOGNOSIA_HOME_STR = os.environ.get("AUTOGNOSIA_HOME", str(Path.home() / ".autognosia"))
AUTOGNOSIA_HOME = Path(AUTOGNOSIA_HOME_STR)
ACTIVE_WIKI = AUTOGNOSIA_HOME / "active-wiki"
ORACLE_BRAIN = AUTOGNOSIA_HOME / "oracle" / "brain"
MAIN_GRAPH_OUT = AUTOGNOSIA_HOME / "graphify-main-out"
ORACLE_GRAPH_OUT = AUTOGNOSIA_HOME / "graphify-oracle-out"
CONFIG_FILE = AUTOGNOSIA_HOME / "graphify-config.env"

def ensure_directories():
    """Create all required directory structure. Cross-platform."""
    dirs = [
        ACTIVE_WIKI / "projects",
        ACTIVE_WIKI / ".meta",
        ORACLE_BRAIN.parent,  # oracle/
        ORACLE_BRAIN,
        AUTOGNOSIA_HOME / "oracle" / "raw" / "research",
        AUTOGNOSIA_HOME / "oracle" / "raw" / "documents",
        AUTOGNOSIA_HOME / "oracle" / "raw" / "articles",
        AUTOGNOSIA_HOME / "oracle" / "raw" / "transcripts",
        AUTOGNOSIA_HOME / "oracle" / "raw" / "conversations",
        AUTOGNOSIA_HOME / "oracle" / "raw" / "imports",
        AUTOGNOSIA_HOME / "oracle" / "raw" / "assets",
        AUTOGNOSIA_HOME / "backups",
        AUTOGNOSIA_HOME / "secrets",
        MAIN_GRAPH_OUT.parent,
        ORACLE_GRAPH_OUT.parent,
    ]
    created = []
    for d in dirs:
        if not d.exists():
            d.mkdir(parents=True, exist_ok=True)
            created.append(str(d))
    return created

def set_secrets_permissions():
    """Set 700 permissions on secrets directory if it exists."""
    secrets_dir = PERSONAL_AGENT / "secrets"
    if secrets_dir.exists():
        os.chmod(str(secrets_dir), 0o700)
        print(f"  [permissions] secrets directory: 700")

def check_graphify():
    """Check if graphify CLI is available."""
    cmd = ["which", "graphify"] if os.name != 'nt' else ["where", "graphify"]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True)
        if result.returncode != 0:
            print("graphify CLI not found. Install with:")
            print("  uv tool install graphifyy")
            print("  graphify install")
            return False
        return True
    except Exception as e:
        print(f"Error checking graphify: {e}")
        return False

def init_config():
    """Create graphify config file."""
    config = f"""# Graphify Configuration for Autognosia
# Generated by init_graphify.py

GRAPHIFY_MAIN_GRAPH={MAIN_GRAPH_OUT}
GRAPHIFY_ORACLE_GRAPH={ORACLE_GRAPH_OUT}
GRAPHIFY_MAIN_SOURCE={ACTIVE_WIKI}
GRAPHIFY_ORACLE_SOURCE={ORACLE_BRAIN}

# Extraction settings
GRAPHIFY_RECURSIVE=true
GRAPHIFY_FOLLOW_LINKS=true
GRAPHIFY_MIN_NODE_LENGTH=3

# Update settings
GRAPHIFY_INCREMENTAL=true
GRAPHIFY_TRACK_CHANGES=true
"""
    os.makedirs(os.path.dirname(CONFIG_FILE), exist_ok=True)
    with open(CONFIG_FILE, "w", encoding="utf-8") as f:
        f.write(config)
    print(f"[OK] Config written to: {CONFIG_FILE}")

def init_graphs():
    """Run initial extraction for both graphs."""
    os.makedirs(MAIN_GRAPH_OUT, exist_ok=True)
    os.makedirs(ORACLE_GRAPH_OUT, exist_ok=True)
    
    # Check if wikis have content
    if os.path.isdir(ACTIVE_WIKI) and os.listdir(ACTIVE_WIKI):
        print(f"\nExtracting Main Graph from {ACTIVE_WIKI}...")
        result = subprocess.run(
            ["graphify", "extract", ACTIVE_WIKI, "--output", MAIN_GRAPH_OUT],
            capture_output=True, text=True
        )
        if result.returncode == 0:
            print(f"  [OK] Main Graph extracted to: {MAIN_GRAPH_OUT}")
        else:
            print(f"  [WARN] Extraction returned code {result.returncode}")
            if result.stderr:
                print(f"  {result.stderr[:200]}")
    else:
        print(f"\nActive Wiki is empty. Skipping Main Graph extraction.")
    
    if os.path.isdir(ORACLE_BRAIN) and os.listdir(ORACLE_BRAIN):
        print(f"\nExtracting Oracle Graph from {ORACLE_BRAIN}...")
        result = subprocess.run(
            ["graphify", "extract", ORACLE_BRAIN, "--output", ORACLE_GRAPH_OUT],
            capture_output=True, text=True
        )
        if result.returncode == 0:
            print(f"  [OK] Oracle Graph extracted to: {ORACLE_GRAPH_OUT}")
        else:
            print(f"  [WARN] Extraction returned code {result.returncode}")
            if result.stderr:
                print(f"  {result.stderr[:200]}")
    else:
        print(f"\nOracle Brain is empty. Skipping Oracle Graph extraction.")

def verify():
    """Verify graphs were created."""
    print("\nVerification:")
    for name, path in [("Main Graph", MAIN_GRAPH_OUT), ("Oracle Graph", ORACLE_GRAPH_OUT)]:
        if os.path.isdir(path) and os.listdir(path):
            print(f"  [OK] {name}: {path}")
        else:
            print(f"  [--] {name}: empty or not yet generated")

def main():
    print("=== Graphify Initialization ===\n")
    
    graphify_available = check_graphify()
    
    if not graphify_available:
        print("Skipping graph extraction (graphify CLI not installed). Config will still be written.")
    
    init_config()
    
    if graphify_available:
        init_graphs()
    else:
        print("[skip] init_graphs() — graphify CLI not installed")
    
    verify()
    set_secrets_permissions()
    
    print("\nNext steps:")
    print("  1. Ingest wiki content")
    print("  2. Run graph extraction: graphify extract active-wiki/ --out graphify-main-out")
    return 0

if __name__ == "__main__":
    sys.exit(main())
